window.PRIMEQK_CLIENT_CONFIG = {
  productKey: "neo",
  productName: "素数大富豪NEO",
  lobbyName: "NEOロビー",
  wsUrl: "wss://web-production-c8e68.up.railway.app/ws/neo",
  shareUrl: "https://greenplus.github.io/qkneo/",
  shareHashtag: "素数大富豪NEO",
  maxRoomPlayers: 10,
  defaultRoomGroupKey: "beginner",
  defaultRoomKey: "beginner1",
  roomGroupOrder: ["beginner", "advanced"],
  roomGroups: {
    beginner: {
      label: "初級",
      roomKeys: ["beginner1", "beginner2", "beginner3"],
    },
    advanced: {
      label: "上級",
      roomKeys: ["advanced1", "advanced2", "advanced3"],
    },
  },
  rooms: {
    beginner1: {
      roomId: "room_16",
      roomGroupKey: "beginner",
      roomNumber: 1,
      label: "初級",
      title: "7枚 / 偶数半減",
      summary: "ペナルティ1枚",
      badge: "7枚 / 偶数半減 / ペナルティ1枚",
      defaultSampleKey: "neo_beginner_prime_table",
      defaultCpuKey: "gold_planner",
    },
    beginner2: {
      roomId: "room_17",
      roomGroupKey: "beginner",
      roomNumber: 2,
      label: "初級",
      title: "7枚 / 偶数半減",
      summary: "ペナルティ1枚",
      badge: "7枚 / 偶数半減 / ペナルティ1枚",
      defaultSampleKey: "neo_beginner_prime_table",
      defaultCpuKey: "gold_planner",
    },
    beginner3: {
      roomId: "room_18",
      roomGroupKey: "beginner",
      roomNumber: 3,
      label: "初級",
      title: "7枚 / 偶数半減",
      summary: "ペナルティ1枚",
      badge: "7枚 / 偶数半減 / ペナルティ1枚",
      defaultSampleKey: "neo_beginner_prime_table",
      defaultCpuKey: "gold_planner",
    },
    advanced1: {
      roomId: "room_14",
      roomGroupKey: "advanced",
      roomNumber: 1,
      label: "上級",
      title: "11枚 / 通常",
      summary: "ペナルティ通常",
      badge: "11枚 / 通常",
      defaultSampleKey: "sashimi2024",
    },
    advanced2: {
      roomId: "room_19",
      roomGroupKey: "advanced",
      roomNumber: 2,
      label: "上級",
      title: "11枚 / 通常",
      summary: "ペナルティ通常",
      badge: "11枚 / 通常",
      defaultSampleKey: "sashimi2024",
    },
    advanced3: {
      roomId: "room_20",
      roomGroupKey: "advanced",
      roomNumber: 3,
      label: "上級",
      title: "11枚 / 通常",
      summary: "ペナルティ通常",
      badge: "11枚 / 通常",
      defaultSampleKey: "sashimi2024",
    },
  },
  defaultSampleKey: "sashimi2024",
  features: {
    assist: true,
    registration: true,
    hnpChallenge: true,
    campaign: true,
    largestPrimeShare: true,
    globalChat: true,
    recruitment: true,
  },
};
